# Generated by Django 4.0.4 on 2022-04-23 12:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saleslog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='saleslog.guild'),
        ),
        migrations.AddField(
            model_name='listing',
            name='post_date',
            field=models.DateTimeField(default=datetime.date(2022, 4, 23)),
        ),
        migrations.AddField(
            model_name='listing',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 23)),
        ),
    ]
