# Generated by Django 4.0.4 on 2022-04-23 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleslog', '0003_alter_listing_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='post_date',
            field=models.DateTimeField(default=datetime.date(2022, 4, 23)),
        ),
    ]
