# Generated by Django 4.0.4 on 2022-04-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleslog', '0004_alter_listing_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='store_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='saleslog.location', unique=True),
        ),
        migrations.RemoveField(
            model_name='character',
            name='guild',
        ),
        migrations.AddField(
            model_name='character',
            name='guild',
            field=models.ManyToManyField(blank=True, null=True, to='saleslog.guild'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
